version: 2
tools:
  golint: &golint
    lint-command: "golint ${INPUT} | sed 's/^/h:/'"
    lint-ignore-exit-code: true
    lint-formats:
      - '%t:%f:%l:%c:%m'

  vint: &vint
    lint-command: 'vint -'
    lint-stdin: true

languages:
  go:
    - <<: *golint

  vim:
    - <<: *vint
