snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git diff
    keyword: gd
    snippet: git diff
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'

completions:
  - name: kill
    patterns:
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
  - name: git branch
    patterns:
      - "^git switch $"
      - "^gb $"
    sourceCommand: "git branch --all | grep -v '* '"
    options:
      --prompt: "'Switch Branch> '"
    callback: "awk '{print $1}'"
  - name: editor
    patterns:
      - "^(nvim|v) $"
    sourceCommand: "find . -type f"
    options:
      --prompt: "'Edit file> '"
  - name: gcloud configuration
    patterns:
      - "^gcloud config configurations activate $"
    sourceCommand: "gcloud config configurations list --format='value(name)'"
    options:
      --prompt: "'Activate Configuration> '"
  - name: change dir
    patterns:
      - "^(cd) $"
    sourceCommand: "find . -type d"
    options:
      --prompt: "'Directory> '"
