snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'

completions:
  - name: kill
    patterns:
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
  - name: git branch
    patterns:
      - "^git switch $"
      - "^gb $"
    sourceCommand: "git branch --all | grep -v '* '"
    options:
      --prompt: "'Switch Branch> '"
    callback: "awk '{print $1}'"
