[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
hook_add = '''
if executable('golsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'golsp',
        \ 'cmd': {server_info->['golsp', '-mode', 'stdio']},
        \ 'whitelist': ['go'],
        \ })
endif
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
let g:asyncomplete_log_file = expand('~/.config/nvim/dein/asyncomplete.log')
let g:asyncomplete_auto_popup = 1
let g:lsp_async_completion = 1
let g:asyncomplete_remove_duplicates = 1
source ~/.config/nvim/dein/repos/github.com/prabirshrestha/asyncomplete.vim/autoload/asyncomplete.vim
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-ultisnips.vim'
depends = ['asyncomplete.vim']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = ['vim-lsp', 'asyncomplete.vim']
merged = 0
hook_add = '''
let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/.config/nvim/dein/vim-lsp.log')
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
let g:airline_theme='luna'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\   'tex': {
\       'command': 'latexmk',
\       'exec': ['%c -c -gg -pdfdvi %s', 'open %s:r.pdf']
\   },
\}
'''

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = 'nginx'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# Gbrowseを出来るようにする
[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'junegunn/fzf'
build = './install'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['junegunn/fzf']

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
