[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
hook_add = '''
nmap <silent> <C-u><C-t> :<C-u>Denite filetype<CR>  # filetypeを変更します
nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>  # カレントディレクトリ以下のファイル
nmap <silent> <C-u><C-l> :<C-u>Denite line<CR>  # 現在のファイルのラインを検索
nmap <silent> <C-u><C-g> :<C-u>Denite grep<CR>  # カレントディレクトリの単語検索
nmap <silent> <C-u><C-]> :<C-u>DeniteCursorWord grep<CR>  # 検索結果（カーソル以下の文字をインプットにする）
nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR> # 最近開いたバッファ（neomru.vim依存）
nmap <silent> <C-u><C-y> :<C-u>Denite neoyank<CR> # ヤンクの履歴（neoyank.vim依存）
nmap <silent> <C-u><C-r> :<C-u>Denite -resume<CR> # 前回のDeniteバッファを再表示する
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
" 横割りオープンを`<C-s>`
call denite#custom#map('_', '<C-s>', '<denite:do_action:split>')
" 縦割りオープンを`<C-v>`
call denite#custom#map('_', '<C-v>', '<denite:do_action:vsplit>')
" タブオープンを`<C-t>`
call denite#custom#map('_', '<C-t>', '<denite:do_action:tabopen>')
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
autocmd FileType defx call s:defx_my_settings()
function! s:defx_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ defx#do_action('open')
  nnoremap <silent><buffer><expr> c
  \ defx#do_action('copy')
  nnoremap <silent><buffer><expr> m
  \ defx#do_action('move')
  nnoremap <silent><buffer><expr> p
  \ defx#do_action('paste')
  nnoremap <silent><buffer><expr> <C-v>
  \ defx#do_action('open', 'vsplit')
  nnoremap <silent><buffer><expr> K
  \ defx#do_action('new_directory')
  nnoremap <silent><buffer><expr> N
  \ defx#do_action('new_file')
  nnoremap <silent><buffer><expr> .
  \ defx#do_action('toggle_ignored_files')
  nnoremap <silent><buffer><expr> d
  \ defx#do_action('remove')
  nnoremap <silent><buffer><expr> r
  \ defx#do_action('rename')
  nnoremap <silent><buffer><expr> yy
  \ defx#do_action('yank_path')
  nnoremap <silent><buffer><expr> h
  \ defx#do_action('cd', ['..'])
  nnoremap <silent><buffer><expr> ~
  \ defx#do_action('cd')
  nnoremap <silent><buffer><expr> q
  \ defx#do_action('quit')
endfunction
nmap <silent> <C-u><C-d> :<C-u>Defx<CR>  # filetypeを変更します
nmap <silent> <C-u><C-v> :<C-u>Defx -split='vertical'<CR>  # filetypeを変更します
'''

# vim-surroundを.で繰り返せるようにする。
[[plugins]]
repo = 'tpope/vim-repeat'
hook_post_source = '''
  silent! call repeat#set("\<Plug>MyWonderfulMap", v:count)
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
