[tools]
go = 'latest'
ghq = 'latest'
deno = "latest"
fzf = 'latest'
gh = 'latest'
"aqua:neovim/neovim" = "latest"
node = 'latest'
rust = 'latest'
tmux = 'latest'
eza = "latest"
lazygit = "latest"
ripgrep = "latest"
direnv = "latest"
poetry = "latest"
yq = "latest"
"npm:@google/gemini-cli" = "latest"
mysqldef = "latest"
fd = "latest"
python = "3.13"
"pipx:mcp-obsidian" = "latest"
duckdb = "latest"
uv = "latest"
gcloud = "latest"
bun = "latest"
bat = "latest"
delta = "latest"
"pipx:pyrefly" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"go:github.com/k1LoW/tcmux" = "latest"
tree-sitter = "latest"
"npm:dotenv-cli" = "latest"
k9s = "latest"
git-lfs = "latest"
pnpm = "latest"
pinact = "latest"
helm = "latest"
"npm:@googleworkspace/cli" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform"]
experimental = true
